FROM debian
MAINTAINER VividCloud

COPY . /app/
WORKDIR /app

RUN apt-get update && apt-get install curl -y
RUN curl https://install.meteor.com | sh
RUN meteor npm i && meteor build --server-only --directory /
